//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadanie_3.MatrixGen {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatrixGen.IMatrixGen")]
    public interface IMatrixGen {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/generateMatrixM", ReplyAction="http://tempuri.org/IMatrixGen/generateMatrixMResponse")]
        Zadanie_3.MatrixGen.generateMatrixMResponse generateMatrixM(Zadanie_3.MatrixGen.generateMatrixMRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/generateMatrixM", ReplyAction="http://tempuri.org/IMatrixGen/generateMatrixMResponse")]
        System.Threading.Tasks.Task<Zadanie_3.MatrixGen.generateMatrixMResponse> generateMatrixMAsync(Zadanie_3.MatrixGen.generateMatrixMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/generateMatrixID", ReplyAction="http://tempuri.org/IMatrixGen/generateMatrixIDResponse")]
        serviceCommon.sServiceRespExt generateMatrixID(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/generateMatrixID", ReplyAction="http://tempuri.org/IMatrixGen/generateMatrixIDResponse")]
        System.Threading.Tasks.Task<serviceCommon.sServiceRespExt> generateMatrixIDAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/getMatrixFromID", ReplyAction="http://tempuri.org/IMatrixGen/getMatrixFromIDResponse")]
        serviceCommon.CMatrix getMatrixFromID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatrixGen/getMatrixFromID", ReplyAction="http://tempuri.org/IMatrixGen/getMatrixFromIDResponse")]
        System.Threading.Tasks.Task<serviceCommon.CMatrix> getMatrixFromIDAsync(int ID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateMatrixM", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class generateMatrixMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public serviceCommon.CMatrix a_out_Matrix;
        
        public generateMatrixMRequest() {
        }
        
        public generateMatrixMRequest(serviceCommon.CMatrix a_out_Matrix) {
            this.a_out_Matrix = a_out_Matrix;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateMatrixMResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class generateMatrixMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public serviceCommon.sServiceResp generateMatrixMResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public serviceCommon.CMatrix a_out_Matrix;
        
        public generateMatrixMResponse() {
        }
        
        public generateMatrixMResponse(serviceCommon.sServiceResp generateMatrixMResult, serviceCommon.CMatrix a_out_Matrix) {
            this.generateMatrixMResult = generateMatrixMResult;
            this.a_out_Matrix = a_out_Matrix;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatrixGenChannel : Zadanie_3.MatrixGen.IMatrixGen, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatrixGenClient : System.ServiceModel.ClientBase<Zadanie_3.MatrixGen.IMatrixGen>, Zadanie_3.MatrixGen.IMatrixGen {
        
        public MatrixGenClient() {
        }
        
        public MatrixGenClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatrixGenClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixGenClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatrixGenClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zadanie_3.MatrixGen.generateMatrixMResponse Zadanie_3.MatrixGen.IMatrixGen.generateMatrixM(Zadanie_3.MatrixGen.generateMatrixMRequest request) {
            return base.Channel.generateMatrixM(request);
        }
        
        public serviceCommon.sServiceResp generateMatrixM(ref serviceCommon.CMatrix a_out_Matrix) {
            Zadanie_3.MatrixGen.generateMatrixMRequest inValue = new Zadanie_3.MatrixGen.generateMatrixMRequest();
            inValue.a_out_Matrix = a_out_Matrix;
            Zadanie_3.MatrixGen.generateMatrixMResponse retVal = ((Zadanie_3.MatrixGen.IMatrixGen)(this)).generateMatrixM(inValue);
            a_out_Matrix = retVal.a_out_Matrix;
            return retVal.generateMatrixMResult;
        }
        
        public System.Threading.Tasks.Task<Zadanie_3.MatrixGen.generateMatrixMResponse> generateMatrixMAsync(Zadanie_3.MatrixGen.generateMatrixMRequest request) {
            return base.Channel.generateMatrixMAsync(request);
        }
        
        public serviceCommon.sServiceRespExt generateMatrixID(int x, int y) {
            return base.Channel.generateMatrixID(x, y);
        }
        
        public System.Threading.Tasks.Task<serviceCommon.sServiceRespExt> generateMatrixIDAsync(int x, int y) {
            return base.Channel.generateMatrixIDAsync(x, y);
        }
        
        public serviceCommon.CMatrix getMatrixFromID(int ID) {
            return base.Channel.getMatrixFromID(ID);
        }
        
        public System.Threading.Tasks.Task<serviceCommon.CMatrix> getMatrixFromIDAsync(int ID) {
            return base.Channel.getMatrixFromIDAsync(ID);
        }
    }
}
